import type { Metadata } from "next";
// eslint-disable-next-line camelcase
import { Geist, Geist_Mono } from "next/font/google";
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";

import CraftoProvider from "@/frontend/_providers/CraftoProvider";
import ReactSlickProvider from "@/frontend/_providers/ReactSlickProvider";
import { routing } from "@/i18n/routing";
import { initPayload } from "@/app/api/utils/getPayload";
import Footer from "../../_components/footer";

import "@/frontend/globals.css";
import { headers } from "next/headers";

// Server-side'da çalışacak async fonksiyon
async function getFooterData() {
  try {
    const payload = await initPayload();
    // Tüm diller için veriyi çek
    const locales = ["en", "tr"];
    const footerData: any = { content: {} };

    // Her dil için ayrı ayrı veri çek
    for (const locale of locales) {
      const response = await payload.findGlobal({
        slug: "footer",
        locale: locale as "en" | "tr" | "all",
      });

      // Her dilin verisini content altında o dilin key'i ile sakla
      if (response?.content) {
        footerData.content[locale] = response.content;
      }
    }

    return footerData;
  } catch (error) {
    console.error("Error fetching footer data:", error);
    return null;
  }
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params: paramsPromise,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const params = await paramsPromise;
  const { locale } = params;

  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  setRequestLocale(locale);

  // Client tarafına mesajları gönder
  const messages = await getMessages();

  // Footer verilerini REST API üzerinden çek
  const footerData = await getFooterData();

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          <CraftoProvider>
            <ReactSlickProvider>
              {children}
              {footerData && <Footer footerData={footerData} />}
            </ReactSlickProvider>
          </CraftoProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}
