/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    users: User;
    media: Media;
    'privacy-policy': PrivacyPolicy;
    sliders: Slider;
    partners: Partner;
    'content-with-image': ContentWithImage;
    'media-block': MediaBlock;
    counter: Counter;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'privacy-policy': PrivacyPolicySelect<false> | PrivacyPolicySelect<true>;
    sliders: SlidersSelect<false> | SlidersSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'content-with-image': ContentWithImageSelect<false> | ContentWithImageSelect<true>;
    'media-block': MediaBlockSelect<false> | MediaBlockSelect<true>;
    counter: CounterSelect<false> | CounterSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: 'tr' | 'en';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy".
 */
export interface PrivacyPolicy {
  id: number;
  title: string;
  sections: {
    legalDisclaimer: {
      title: string;
      content: string;
    };
    basics: {
      title: string;
      content: string;
    };
    inclusion: {
      title: string;
      content: string;
    };
  };
  translations?: {
    tr?: {
      title?: string | null;
      sections?: {
        legalDisclaimer?: {
          title?: string | null;
          content?: string | null;
        };
        basics?: {
          title?: string | null;
          content?: string | null;
        };
        inclusion?: {
          title?: string | null;
          content?: string | null;
        };
      };
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sliders".
 */
export interface Slider {
  id: number;
  title: string;
  slides: {
    title: string;
    description?: string | null;
    image: number | Media;
    buttonText?: string | null;
    buttonLink?: string | null;
    id?: string | null;
  }[];
  translations?: {
    tr?: {
      slides?:
        | {
            title?: string | null;
            description?: string | null;
            buttonText?: string | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  /**
   * Bu slider aktif mi?
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  logo: number | Media;
  order?: number | null;
  /**
   * Show/hide this partner
   */
  active?: boolean | null;
  url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-with-image".
 */
export interface ContentWithImage {
  id: number;
  /**
   * Title
   */
  title: string;
  /**
   * Description
   */
  description?: string | null;
  image: number | Media;
  /**
   * Button Text
   */
  buttonText?: string | null;
  /**
   * Button Link
   */
  buttonLink?: string | null;
  order?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-block".
 */
export interface MediaBlock {
  id: number;
  title: string;
  description?: string | null;
  media: number | Media;
  buttonText?: string | null;
  /**
   * Enter the URL for button (e.g., /contact, https://example.com)
   */
  buttonLink?: string | null;
  translations?: {
    tr?: {
      title?: string | null;
      description?: string | null;
      buttonText?: string | null;
      buttonLink?: string | null;
    };
  };
  /**
   * Toggle to show/hide this media block
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "counter".
 */
export interface Counter {
  id: number;
  title: string;
  items?:
    | {
        description: string;
        value: number;
        id?: string | null;
      }[]
    | null;
  translations?: {
    tr?: {
      title?: string | null;
      items?:
        | {
            description?: string | null;
            value?: number | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  /**
   * Toggle to show/hide this counter section
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'privacy-policy';
        value: number | PrivacyPolicy;
      } | null)
    | ({
        relationTo: 'sliders';
        value: number | Slider;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'content-with-image';
        value: number | ContentWithImage;
      } | null)
    | ({
        relationTo: 'media-block';
        value: number | MediaBlock;
      } | null)
    | ({
        relationTo: 'counter';
        value: number | Counter;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy_select".
 */
export interface PrivacyPolicySelect<T extends boolean = true> {
  title?: T;
  sections?:
    | T
    | {
        legalDisclaimer?:
          | T
          | {
              title?: T;
              content?: T;
            };
        basics?:
          | T
          | {
              title?: T;
              content?: T;
            };
        inclusion?:
          | T
          | {
              title?: T;
              content?: T;
            };
      };
  translations?:
    | T
    | {
        tr?:
          | T
          | {
              title?: T;
              sections?:
                | T
                | {
                    legalDisclaimer?:
                      | T
                      | {
                          title?: T;
                          content?: T;
                        };
                    basics?:
                      | T
                      | {
                          title?: T;
                          content?: T;
                        };
                    inclusion?:
                      | T
                      | {
                          title?: T;
                          content?: T;
                        };
                  };
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sliders_select".
 */
export interface SlidersSelect<T extends boolean = true> {
  title?: T;
  slides?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        buttonText?: T;
        buttonLink?: T;
        id?: T;
      };
  translations?:
    | T
    | {
        tr?:
          | T
          | {
              slides?:
                | T
                | {
                    title?: T;
                    description?: T;
                    buttonText?: T;
                    id?: T;
                  };
            };
      };
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  order?: T;
  active?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-with-image_select".
 */
export interface ContentWithImageSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  buttonText?: T;
  buttonLink?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-block_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  media?: T;
  buttonText?: T;
  buttonLink?: T;
  translations?:
    | T
    | {
        tr?:
          | T
          | {
              title?: T;
              description?: T;
              buttonText?: T;
              buttonLink?: T;
            };
      };
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "counter_select".
 */
export interface CounterSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        description?: T;
        value?: T;
        id?: T;
      };
  translations?:
    | T
    | {
        tr?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    description?: T;
                    value?: T;
                    id?: T;
                  };
            };
      };
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}