/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  serial,
  varchar,
  timestamp,
  numeric,
  integer,
  jsonb,
  text,
  boolean,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum__locales = pgEnum("enum__locales", ["en", "tr"]);
export const enum_homepage_blocks_content_with_image_block_position = pgEnum(
  "enum_homepage_blocks_content_with_image_block_position",
  ["left", "right"],
);
export const enum_homepage_blocks_icon_list_block_items_icon = pgEnum(
  "enum_homepage_blocks_icon_list_block_items_icon",
  [
    "GiWorld",
    "CiDiscount1",
    "GiWaterRecycling",
    "LuFootprints",
    "IoQrCodeOutline",
    "GiConversation",
  ],
);

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts").default("0"),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => ({
    users_updated_at_idx: index("users_updated_at_idx").on(columns.updatedAt),
    users_created_at_idx: index("users_created_at_idx").on(columns.createdAt),
    users_email_idx: uniqueIndex("users_email_idx").on(columns.email),
  }),
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize"),
    width: numeric("width"),
    height: numeric("height"),
    focalX: numeric("focal_x"),
    focalY: numeric("focal_y"),
  },
  (columns) => ({
    media_updated_at_idx: index("media_updated_at_idx").on(columns.updatedAt),
    media_created_at_idx: index("media_created_at_idx").on(columns.createdAt),
    media_filename_idx: uniqueIndex("media_filename_idx").on(columns.filename),
  }),
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_locked_documents_global_slug_idx: index(
      "payload_locked_documents_global_slug_idx",
    ).on(columns.globalSlug),
    payload_locked_documents_updated_at_idx: index(
      "payload_locked_documents_updated_at_idx",
    ).on(columns.updatedAt),
    payload_locked_documents_created_at_idx: index(
      "payload_locked_documents_created_at_idx",
    ).on(columns.createdAt),
  }),
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
    mediaID: integer("media_id"),
  },
  (columns) => ({
    order: index("payload_locked_documents_rels_order_idx").on(columns.order),
    parentIdx: index("payload_locked_documents_rels_parent_idx").on(
      columns.parent,
    ),
    pathIdx: index("payload_locked_documents_rels_path_idx").on(columns.path),
    payload_locked_documents_rels_users_id_idx: index(
      "payload_locked_documents_rels_users_id_idx",
    ).on(columns.usersID),
    payload_locked_documents_rels_media_id_idx: index(
      "payload_locked_documents_rels_media_id_idx",
    ).on(columns.mediaID),
    parentFk: foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    usersIdFk: foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    mediaIdFk: foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
  }),
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_preferences_key_idx: index("payload_preferences_key_idx").on(
      columns.key,
    ),
    payload_preferences_updated_at_idx: index(
      "payload_preferences_updated_at_idx",
    ).on(columns.updatedAt),
    payload_preferences_created_at_idx: index(
      "payload_preferences_created_at_idx",
    ).on(columns.createdAt),
  }),
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => ({
    order: index("payload_preferences_rels_order_idx").on(columns.order),
    parentIdx: index("payload_preferences_rels_parent_idx").on(columns.parent),
    pathIdx: index("payload_preferences_rels_path_idx").on(columns.path),
    payload_preferences_rels_users_id_idx: index(
      "payload_preferences_rels_users_id_idx",
    ).on(columns.usersID),
    parentFk: foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    usersIdFk: foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  }),
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_migrations_updated_at_idx: index(
      "payload_migrations_updated_at_idx",
    ).on(columns.updatedAt),
    payload_migrations_created_at_idx: index(
      "payload_migrations_created_at_idx",
    ).on(columns.createdAt),
  }),
);

export const homepage_blocks_content_with_image_block = pgTable(
  "homepage_blocks_content_with_image_block",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: varchar("id").primaryKey(),
    image: integer("image_id")
      .notNull()
      .references(() => media.id, {
        onDelete: "set null",
      }),
    position:
      enum_homepage_blocks_content_with_image_block_position(
        "position",
      ).default("left"),
    blockOptions_title: varchar("block_options_title"),
    blockOptions_description: varchar("block_options_description"),
    blockOptions_heroContent: jsonb("block_options_hero_content"),
    blockOptions_footerContent: jsonb("block_options_footer_content"),
    blockOptions_innerContainer: boolean(
      "block_options_inner_container",
    ).default(true),
    blockName: varchar("block_name"),
  },
  (columns) => ({
    _orderIdx: index("homepage_blocks_content_with_image_block_order_idx").on(
      columns._order,
    ),
    _parentIDIdx: index(
      "homepage_blocks_content_with_image_block_parent_id_idx",
    ).on(columns._parentID),
    _pathIdx: index("homepage_blocks_content_with_image_block_path_idx").on(
      columns._path,
    ),
    homepage_blocks_content_with_image_block_image_idx: index(
      "homepage_blocks_content_with_image_block_image_idx",
    ).on(columns.image),
    _parentIdFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [homepage.id],
      name: "homepage_blocks_content_with_image_block_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const homepage_blocks_content_with_image_block_locales = pgTable(
  "homepage_blocks_content_with_image_block_locales",
  {
    title: varchar("title").notNull(),
    description: varchar("description"),
    buttonText: varchar("button_text"),
    buttonLink: varchar("button_link"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: varchar("_parent_id").notNull(),
  },
  (columns) => ({
    _localeParent: uniqueIndex(
      "homepage_blocks_content_with_image_block_locales_locale_parent_id_unique",
    ).on(columns._locale, columns._parentID),
    _parentIdFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [homepage_blocks_content_with_image_block.id],
      name: "homepage_blocks_content_with_image_block_locales_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const homepage_blocks_slider_block_sliders = pgTable(
  "homepage_blocks_slider_block_sliders",
  {
    _order: integer("_order").notNull(),
    _parentID: varchar("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    image: integer("image_id")
      .notNull()
      .references(() => media.id, {
        onDelete: "set null",
      }),
  },
  (columns) => ({
    _orderIdx: index("homepage_blocks_slider_block_sliders_order_idx").on(
      columns._order,
    ),
    _parentIDIdx: index(
      "homepage_blocks_slider_block_sliders_parent_id_idx",
    ).on(columns._parentID),
    homepage_blocks_slider_block_sliders_image_idx: index(
      "homepage_blocks_slider_block_sliders_image_idx",
    ).on(columns.image),
    _parentIDFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [homepage_blocks_slider_block.id],
      name: "homepage_blocks_slider_block_sliders_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const homepage_blocks_slider_block_sliders_locales = pgTable(
  "homepage_blocks_slider_block_sliders_locales",
  {
    title: varchar("title").notNull(),
    description: varchar("description").notNull(),
    buttonText: varchar("button_text"),
    buttonLink: varchar("button_link"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: varchar("_parent_id").notNull(),
  },
  (columns) => ({
    _localeParent: uniqueIndex(
      "homepage_blocks_slider_block_sliders_locales_locale_parent_id_unique",
    ).on(columns._locale, columns._parentID),
    _parentIdFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [homepage_blocks_slider_block_sliders.id],
      name: "homepage_blocks_slider_block_sliders_locales_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const homepage_blocks_slider_block_clients = pgTable(
  "homepage_blocks_slider_block_clients",
  {
    _order: integer("_order").notNull(),
    _parentID: varchar("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    image: integer("image_id")
      .notNull()
      .references(() => media.id, {
        onDelete: "set null",
      }),
  },
  (columns) => ({
    _orderIdx: index("homepage_blocks_slider_block_clients_order_idx").on(
      columns._order,
    ),
    _parentIDIdx: index(
      "homepage_blocks_slider_block_clients_parent_id_idx",
    ).on(columns._parentID),
    homepage_blocks_slider_block_clients_image_idx: index(
      "homepage_blocks_slider_block_clients_image_idx",
    ).on(columns.image),
    _parentIDFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [homepage_blocks_slider_block.id],
      name: "homepage_blocks_slider_block_clients_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const homepage_blocks_slider_block_clients_locales = pgTable(
  "homepage_blocks_slider_block_clients_locales",
  {
    name: varchar("name").notNull(),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: varchar("_parent_id").notNull(),
  },
  (columns) => ({
    _localeParent: uniqueIndex(
      "homepage_blocks_slider_block_clients_locales_locale_parent_id_unique",
    ).on(columns._locale, columns._parentID),
    _parentIdFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [homepage_blocks_slider_block_clients.id],
      name: "homepage_blocks_slider_block_clients_locales_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const homepage_blocks_slider_block = pgTable(
  "homepage_blocks_slider_block",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: varchar("id").primaryKey(),
    blockName: varchar("block_name"),
  },
  (columns) => ({
    _orderIdx: index("homepage_blocks_slider_block_order_idx").on(
      columns._order,
    ),
    _parentIDIdx: index("homepage_blocks_slider_block_parent_id_idx").on(
      columns._parentID,
    ),
    _pathIdx: index("homepage_blocks_slider_block_path_idx").on(columns._path),
    _parentIdFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [homepage.id],
      name: "homepage_blocks_slider_block_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const homepage_blocks_media_block = pgTable(
  "homepage_blocks_media_block",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: varchar("id").primaryKey(),
    media: integer("media_id").references(() => media.id, {
      onDelete: "set null",
    }),
    blockOptions_title: varchar("block_options_title"),
    blockOptions_description: varchar("block_options_description"),
    blockOptions_heroContent: jsonb("block_options_hero_content"),
    blockOptions_footerContent: jsonb("block_options_footer_content"),
    blockOptions_innerContainer: boolean(
      "block_options_inner_container",
    ).default(true),
    blockName: varchar("block_name"),
  },
  (columns) => ({
    _orderIdx: index("homepage_blocks_media_block_order_idx").on(
      columns._order,
    ),
    _parentIDIdx: index("homepage_blocks_media_block_parent_id_idx").on(
      columns._parentID,
    ),
    _pathIdx: index("homepage_blocks_media_block_path_idx").on(columns._path),
    homepage_blocks_media_block_media_idx: index(
      "homepage_blocks_media_block_media_idx",
    ).on(columns.media),
    _parentIdFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [homepage.id],
      name: "homepage_blocks_media_block_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const homepage_blocks_accordion_block_items = pgTable(
  "homepage_blocks_accordion_block_items",
  {
    _order: integer("_order").notNull(),
    _parentID: varchar("_parent_id").notNull(),
    _locale: enum__locales("_locale").notNull(),
    id: varchar("id").primaryKey(),
    title: varchar("title").notNull(),
    description: varchar("description").notNull(),
  },
  (columns) => ({
    _orderIdx: index("homepage_blocks_accordion_block_items_order_idx").on(
      columns._order,
    ),
    _parentIDIdx: index(
      "homepage_blocks_accordion_block_items_parent_id_idx",
    ).on(columns._parentID),
    _localeIdx: index("homepage_blocks_accordion_block_items_locale_idx").on(
      columns._locale,
    ),
    _parentIDFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [homepage_blocks_accordion_block.id],
      name: "homepage_blocks_accordion_block_items_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const homepage_blocks_accordion_block = pgTable(
  "homepage_blocks_accordion_block",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: varchar("id").primaryKey(),
    image: integer("image_id")
      .notNull()
      .references(() => media.id, {
        onDelete: "set null",
      }),
    blockOptions_title: varchar("block_options_title"),
    blockOptions_description: varchar("block_options_description"),
    blockOptions_heroContent: jsonb("block_options_hero_content"),
    blockOptions_footerContent: jsonb("block_options_footer_content"),
    blockOptions_innerContainer: boolean(
      "block_options_inner_container",
    ).default(true),
    blockName: varchar("block_name"),
  },
  (columns) => ({
    _orderIdx: index("homepage_blocks_accordion_block_order_idx").on(
      columns._order,
    ),
    _parentIDIdx: index("homepage_blocks_accordion_block_parent_id_idx").on(
      columns._parentID,
    ),
    _pathIdx: index("homepage_blocks_accordion_block_path_idx").on(
      columns._path,
    ),
    homepage_blocks_accordion_block_image_idx: index(
      "homepage_blocks_accordion_block_image_idx",
    ).on(columns.image),
    _parentIdFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [homepage.id],
      name: "homepage_blocks_accordion_block_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const homepage_blocks_accordion_block_locales = pgTable(
  "homepage_blocks_accordion_block_locales",
  {
    title: varchar("title").notNull(),
    description: varchar("description").notNull(),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: varchar("_parent_id").notNull(),
  },
  (columns) => ({
    _localeParent: uniqueIndex(
      "homepage_blocks_accordion_block_locales_locale_parent_id_unique",
    ).on(columns._locale, columns._parentID),
    _parentIdFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [homepage_blocks_accordion_block.id],
      name: "homepage_blocks_accordion_block_locales_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const homepage_blocks_icon_list_block_items = pgTable(
  "homepage_blocks_icon_list_block_items",
  {
    _order: integer("_order").notNull(),
    _parentID: varchar("_parent_id").notNull(),
    _locale: enum__locales("_locale").notNull(),
    id: varchar("id").primaryKey(),
    icon: enum_homepage_blocks_icon_list_block_items_icon("icon").notNull(),
    description: varchar("description").notNull(),
  },
  (columns) => ({
    _orderIdx: index("homepage_blocks_icon_list_block_items_order_idx").on(
      columns._order,
    ),
    _parentIDIdx: index(
      "homepage_blocks_icon_list_block_items_parent_id_idx",
    ).on(columns._parentID),
    _localeIdx: index("homepage_blocks_icon_list_block_items_locale_idx").on(
      columns._locale,
    ),
    _parentIDFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [homepage_blocks_icon_list_block.id],
      name: "homepage_blocks_icon_list_block_items_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const homepage_blocks_icon_list_block = pgTable(
  "homepage_blocks_icon_list_block",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: varchar("id").primaryKey(),
    blockOptions_title: varchar("block_options_title"),
    blockOptions_description: varchar("block_options_description"),
    blockOptions_heroContent: jsonb("block_options_hero_content"),
    blockOptions_footerContent: jsonb("block_options_footer_content"),
    blockOptions_innerContainer: boolean(
      "block_options_inner_container",
    ).default(true),
    blockName: varchar("block_name"),
  },
  (columns) => ({
    _orderIdx: index("homepage_blocks_icon_list_block_order_idx").on(
      columns._order,
    ),
    _parentIDIdx: index("homepage_blocks_icon_list_block_parent_id_idx").on(
      columns._parentID,
    ),
    _pathIdx: index("homepage_blocks_icon_list_block_path_idx").on(
      columns._path,
    ),
    _parentIdFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [homepage.id],
      name: "homepage_blocks_icon_list_block_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const homepage = pgTable("homepage", {
  id: serial("id").primaryKey(),
  updatedAt: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
});

export const relations_users = relations(users, () => ({}));
export const relations_media = relations(media, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);
export const relations_homepage_blocks_content_with_image_block_locales =
  relations(homepage_blocks_content_with_image_block_locales, ({ one }) => ({
    _parentID: one(homepage_blocks_content_with_image_block, {
      fields: [homepage_blocks_content_with_image_block_locales._parentID],
      references: [homepage_blocks_content_with_image_block.id],
      relationName: "_locales",
    }),
  }));
export const relations_homepage_blocks_content_with_image_block = relations(
  homepage_blocks_content_with_image_block,
  ({ one, many }) => ({
    _parentID: one(homepage, {
      fields: [homepage_blocks_content_with_image_block._parentID],
      references: [homepage.id],
      relationName: "_blocks_contentWithImageBlock",
    }),
    _locales: many(homepage_blocks_content_with_image_block_locales, {
      relationName: "_locales",
    }),
    image: one(media, {
      fields: [homepage_blocks_content_with_image_block.image],
      references: [media.id],
      relationName: "image",
    }),
  }),
);
export const relations_homepage_blocks_slider_block_sliders_locales = relations(
  homepage_blocks_slider_block_sliders_locales,
  ({ one }) => ({
    _parentID: one(homepage_blocks_slider_block_sliders, {
      fields: [homepage_blocks_slider_block_sliders_locales._parentID],
      references: [homepage_blocks_slider_block_sliders.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_homepage_blocks_slider_block_sliders = relations(
  homepage_blocks_slider_block_sliders,
  ({ one, many }) => ({
    _parentID: one(homepage_blocks_slider_block, {
      fields: [homepage_blocks_slider_block_sliders._parentID],
      references: [homepage_blocks_slider_block.id],
      relationName: "sliders",
    }),
    _locales: many(homepage_blocks_slider_block_sliders_locales, {
      relationName: "_locales",
    }),
    image: one(media, {
      fields: [homepage_blocks_slider_block_sliders.image],
      references: [media.id],
      relationName: "image",
    }),
  }),
);
export const relations_homepage_blocks_slider_block_clients_locales = relations(
  homepage_blocks_slider_block_clients_locales,
  ({ one }) => ({
    _parentID: one(homepage_blocks_slider_block_clients, {
      fields: [homepage_blocks_slider_block_clients_locales._parentID],
      references: [homepage_blocks_slider_block_clients.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_homepage_blocks_slider_block_clients = relations(
  homepage_blocks_slider_block_clients,
  ({ one, many }) => ({
    _parentID: one(homepage_blocks_slider_block, {
      fields: [homepage_blocks_slider_block_clients._parentID],
      references: [homepage_blocks_slider_block.id],
      relationName: "clients",
    }),
    _locales: many(homepage_blocks_slider_block_clients_locales, {
      relationName: "_locales",
    }),
    image: one(media, {
      fields: [homepage_blocks_slider_block_clients.image],
      references: [media.id],
      relationName: "image",
    }),
  }),
);
export const relations_homepage_blocks_slider_block = relations(
  homepage_blocks_slider_block,
  ({ one, many }) => ({
    _parentID: one(homepage, {
      fields: [homepage_blocks_slider_block._parentID],
      references: [homepage.id],
      relationName: "_blocks_sliderBlock",
    }),
    sliders: many(homepage_blocks_slider_block_sliders, {
      relationName: "sliders",
    }),
    clients: many(homepage_blocks_slider_block_clients, {
      relationName: "clients",
    }),
  }),
);
export const relations_homepage_blocks_media_block = relations(
  homepage_blocks_media_block,
  ({ one }) => ({
    _parentID: one(homepage, {
      fields: [homepage_blocks_media_block._parentID],
      references: [homepage.id],
      relationName: "_blocks_mediaBlock",
    }),
    media: one(media, {
      fields: [homepage_blocks_media_block.media],
      references: [media.id],
      relationName: "media",
    }),
  }),
);
export const relations_homepage_blocks_accordion_block_items = relations(
  homepage_blocks_accordion_block_items,
  ({ one }) => ({
    _parentID: one(homepage_blocks_accordion_block, {
      fields: [homepage_blocks_accordion_block_items._parentID],
      references: [homepage_blocks_accordion_block.id],
      relationName: "items",
    }),
  }),
);
export const relations_homepage_blocks_accordion_block_locales = relations(
  homepage_blocks_accordion_block_locales,
  ({ one }) => ({
    _parentID: one(homepage_blocks_accordion_block, {
      fields: [homepage_blocks_accordion_block_locales._parentID],
      references: [homepage_blocks_accordion_block.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_homepage_blocks_accordion_block = relations(
  homepage_blocks_accordion_block,
  ({ one, many }) => ({
    _parentID: one(homepage, {
      fields: [homepage_blocks_accordion_block._parentID],
      references: [homepage.id],
      relationName: "_blocks_accordionBlock",
    }),
    _locales: many(homepage_blocks_accordion_block_locales, {
      relationName: "_locales",
    }),
    image: one(media, {
      fields: [homepage_blocks_accordion_block.image],
      references: [media.id],
      relationName: "image",
    }),
    items: many(homepage_blocks_accordion_block_items, {
      relationName: "items",
    }),
  }),
);
export const relations_homepage_blocks_icon_list_block_items = relations(
  homepage_blocks_icon_list_block_items,
  ({ one }) => ({
    _parentID: one(homepage_blocks_icon_list_block, {
      fields: [homepage_blocks_icon_list_block_items._parentID],
      references: [homepage_blocks_icon_list_block.id],
      relationName: "items",
    }),
  }),
);
export const relations_homepage_blocks_icon_list_block = relations(
  homepage_blocks_icon_list_block,
  ({ one, many }) => ({
    _parentID: one(homepage, {
      fields: [homepage_blocks_icon_list_block._parentID],
      references: [homepage.id],
      relationName: "_blocks_iconListBlock",
    }),
    items: many(homepage_blocks_icon_list_block_items, {
      relationName: "items",
    }),
  }),
);
export const relations_homepage = relations(homepage, ({ many }) => ({
  _blocks_contentWithImageBlock: many(
    homepage_blocks_content_with_image_block,
    {
      relationName: "_blocks_contentWithImageBlock",
    },
  ),
  _blocks_sliderBlock: many(homepage_blocks_slider_block, {
    relationName: "_blocks_sliderBlock",
  }),
  _blocks_mediaBlock: many(homepage_blocks_media_block, {
    relationName: "_blocks_mediaBlock",
  }),
  _blocks_accordionBlock: many(homepage_blocks_accordion_block, {
    relationName: "_blocks_accordionBlock",
  }),
  _blocks_iconListBlock: many(homepage_blocks_icon_list_block, {
    relationName: "_blocks_iconListBlock",
  }),
}));

type DatabaseSchema = {
  enum__locales: typeof enum__locales;
  enum_homepage_blocks_content_with_image_block_position: typeof enum_homepage_blocks_content_with_image_block_position;
  enum_homepage_blocks_icon_list_block_items_icon: typeof enum_homepage_blocks_icon_list_block_items_icon;
  users: typeof users;
  media: typeof media;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  homepage_blocks_content_with_image_block: typeof homepage_blocks_content_with_image_block;
  homepage_blocks_content_with_image_block_locales: typeof homepage_blocks_content_with_image_block_locales;
  homepage_blocks_slider_block_sliders: typeof homepage_blocks_slider_block_sliders;
  homepage_blocks_slider_block_sliders_locales: typeof homepage_blocks_slider_block_sliders_locales;
  homepage_blocks_slider_block_clients: typeof homepage_blocks_slider_block_clients;
  homepage_blocks_slider_block_clients_locales: typeof homepage_blocks_slider_block_clients_locales;
  homepage_blocks_slider_block: typeof homepage_blocks_slider_block;
  homepage_blocks_media_block: typeof homepage_blocks_media_block;
  homepage_blocks_accordion_block_items: typeof homepage_blocks_accordion_block_items;
  homepage_blocks_accordion_block: typeof homepage_blocks_accordion_block;
  homepage_blocks_accordion_block_locales: typeof homepage_blocks_accordion_block_locales;
  homepage_blocks_icon_list_block_items: typeof homepage_blocks_icon_list_block_items;
  homepage_blocks_icon_list_block: typeof homepage_blocks_icon_list_block;
  homepage: typeof homepage;
  relations_users: typeof relations_users;
  relations_media: typeof relations_media;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
  relations_homepage_blocks_content_with_image_block_locales: typeof relations_homepage_blocks_content_with_image_block_locales;
  relations_homepage_blocks_content_with_image_block: typeof relations_homepage_blocks_content_with_image_block;
  relations_homepage_blocks_slider_block_sliders_locales: typeof relations_homepage_blocks_slider_block_sliders_locales;
  relations_homepage_blocks_slider_block_sliders: typeof relations_homepage_blocks_slider_block_sliders;
  relations_homepage_blocks_slider_block_clients_locales: typeof relations_homepage_blocks_slider_block_clients_locales;
  relations_homepage_blocks_slider_block_clients: typeof relations_homepage_blocks_slider_block_clients;
  relations_homepage_blocks_slider_block: typeof relations_homepage_blocks_slider_block;
  relations_homepage_blocks_media_block: typeof relations_homepage_blocks_media_block;
  relations_homepage_blocks_accordion_block_items: typeof relations_homepage_blocks_accordion_block_items;
  relations_homepage_blocks_accordion_block_locales: typeof relations_homepage_blocks_accordion_block_locales;
  relations_homepage_blocks_accordion_block: typeof relations_homepage_blocks_accordion_block;
  relations_homepage_blocks_icon_list_block_items: typeof relations_homepage_blocks_icon_list_block_items;
  relations_homepage_blocks_icon_list_block: typeof relations_homepage_blocks_icon_list_block;
  relations_homepage: typeof relations_homepage;
};

declare module "@payloadcms/db-postgres/types" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
